# configuration
# fill in the course details
 
courseName: Digital Humanities for the Ancient World

# small title that is at the top of every page
subtitle: DHAW2023 | CLAS 32123/1 - CLCV 22123/1 | Fall 2023

# baseurl is the same as the name of the repository
baseurl: /DHAW2023

# url where the required reading is available to download
docsUrl: "" 

# url where the student's grading info is kept
gradingUrl: "" 


# change only if you know what you are doing
collections:
  syllabus:
    output: true
defaults:
  - scope:
      path: ""
      type: syllabus
    values:
      layout: unit
